# Generated by Django 4.2.2 on 2023-07-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicacion_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='subtitle',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='body',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='date',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='title',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(default='Texto de ejemplo'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
