# Generated by Django 4.2.2 on 2023-08-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_publicacion_autor_alter_publicacion_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='body',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='date',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='subtitle',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='contenido',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.publicacion'),
        ),
    ]
